Fixed manger and node - api and websockets, added debugger endpoints
kkingstoun/AMUman pull request #31
Opened 2024-02-21 16:04 UTC by kkingstoun

2024-02-21 16:57 UTC, MathieuMoalic commented on .gitignore
schema.yml should be in the repo, remove from gitignore

2024-02-21 17:25 UTC, MathieuMoalic requested changes
just a few tiny changes and you can merge. The logic seems good

2024-02-21 17:25 UTC, MathieuMoalic commented on manager/amuman/routing.py
remove the file if it's empty

2024-02-21 17:25 UTC, MathieuMoalic commented on manager/manager/forms.py
Remove if unused

2024-02-21 17:25 UTC, MathieuMoalic commented on manager/manager/routing.py
delete unused files

2024-02-21 17:25 UTC, MathieuMoalic commented on manager/manager/serializers.py
if chatgpt can write the comments in english, it might help me understand

2024-02-21 17:25 UTC, MathieuMoalic commented on manager/manager/serializers.py
also there are a lot of dupa in there

2024-02-21 17:25 UTC, MathieuMoalic commented on manager/manager/views.py
A lot of commented out code in there

2024-02-21 17:25 UTC, MathieuMoalic commented on node/amuman_node/main.py
> +if __name__ == "__main__":
I assume this is because of debugpy, can't you just call the entrypoint function here?

2024-02-21 19:57 UTC, kkingstoun commented on .gitignore
OK.

2024-02-22 09:06 UTC, MathieuMoalic approved these changes

2024-02-22 09:17 UTC, merged